from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.home, name='index'),
    path ('/Resources/About/', views.about, name='About'),
    path('/Resources/Team/', views.team, name='Team'),
    path('/Resources/Blog/', views.blog, name='Blog'),
    path('/Resources/CaseStudy/', views.caseStudy, name='CaseStudy'),
    path('/Resources/casestudyHealthCareView/', views.casestudyHealthCareView, name='casestudyHealthCareView'),
    path('/Resources/AwardsCertifications/', views.awardsCertifications, name='AwardsCertifications'),
    path('/Resources/Career/LifeGrandOrtus/', views.lifeGrandOrtus, name='LifeGrandOrtus'),
    path('/Resources/Career/CurrentJobOpening/', views.currentJobOpening, name='CurrentJobOpening'),
    path('/Resources/Career/CSR/', views.csr, name='CSR'),
    path('/Resources/Career/Contact/', views.contactus, name='Contact'),
    path('/Associations/Partners/', views.partners, name='Partners'),
    path('/Associations/Clients/', views.clients, name='Clients'),
    path('/Products/product1desc/', views.productDesc1, name='product1desc'),
    path('/Products/product2desc/', views.productDesc2, name='product2desc'),
    path('/Solutions/FMCG', views.fmcg, name='FMCG'),
    path('/Solutions/Gaming', views.gaming, name='Gaming'),
    path('/Solutions/Healthcare', views.healthcare, name='Healthcare'),
    path('/Solutions/Hospitality', views.hospitality, name='Hospitality'),
    path('/Solutions/ITES', views.ites, name='ITES'),
    path('/Solutions/Manufacturing', views.manufacturing, name='Manufacturing'),
    path('/Solutions/OnDemand', views.onDemand, name='OnDemand'),
    path('/Solutions/Retail', views.retail, name='Retail'),
    path('/Solutions/Staffing', views.staffing, name='Staffing'),
    path('/Solutions/Telecom', views.telecom, name='Telecom'),
    path('/Solutions/Datacenter', views.dataCenter, name='Datacenter'),
    path('/Solutions/FMSAndAMCSupport', views.fmsAndamc, name='FMSAndAMCSupport'),
    path('/Solutions/ImplementationServices', views.implementationServices, name='ImplementationServices'),
    path('/Solutions/Infrastructure', views.infrastructure, name='Infrastructure'),
    path('/Solutions/Internet', views.internet, name='Internet'),
    path('/Solutions/MobilityAndCloud', views.mobilityAndCloud, name='MobilityAndCloud'),
    path('/Solutions/Networking', views.networking, name='Networking'),
    path('/Solutions/ServiceList', views.serviceList, name='ServiceList'),
    path('Windows', views.windowsArticle, name='Windows'),
    path('Cybersecurity', views.cyberSecurity, name='Cybersecurity'),
    path('Ecosystem', views.ecoSystem, name='Ecosystem'),
    path('Exploring', views.exploring, name='Exploring'),
    path('ITservices', views.itService, name='ITservices'),
    path('Transformative', views.transformative, name='Transformative'),
    path('SSEJobOpeningForm', views.sseJobOpeningForm, name='SSEJobOpeningForm'),
    path('UIUXJobOpeningForm', views.uiuxJobOpeningForm, name='UIUXJobOpeningForm'),
    path('DAJobOpeningForm', views.daJobOpeningForm, name='DAJobOpeningForm'),
    path('indexContactForm/', views.indexContactForm, name='indexContactForm'),
    path('jobForm/', views.jobForm, name='jobForm'),
    
]
